### ISSUE TITLE
Propcount should be totalUniqueCount

### ISSUE THREAD

**Issue by gregwhitworth** [nizh914/css-usage#1]
When you have the paragraph that states "There were X" sites you're using the count that we saw property X, this should be the unique viewings. I know we discussed this but I wanted to make sure that I had an issue on it so that when we're showing this it isn't obvious that our math is off.

```
 //PROPERTY COUNT DATA
 propcount.innerHTML = prop.totalUniqueCount;
```

**Comment by rachelnizh** [comment]
Fixed with https://github.com/nizh914/css-usage/commit/2c86ed17bcf4a5203188ab1a06dd806ae256e352. Thanks!
