### ISSUE TITLE
Incorporate this with the site repo

### ISSUE THREAD

**Issue by gregwhitworth** [nizh914/css-usage#2]
In order to setup the API (especially since most of the site is C#) I setup an solution for the proto to live in. Can you put your necessary files into a folder called /site-src/ which will allow you to keep your grunt and build stuff together. We'll want the actual built and necessary items to be in the /content/ dir and index.html to be your HTML (I've got it there already, but wanted to let you put in the necessary content).

**Comment by rachelnizh** [comment]
I no longer need a build system so I did some clean up in https://github.com/nizh914/css-usage/commit/aadf0e165b782d5dfbe24a8a0cc9cea1dbed037b. Pushed to private repo.
